services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222

  client_gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  product-ms:
    build: ./products-microservice
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # order-ms:
  #   depends_on:
  #     - order-db
  #   build: ./orders-microservice
  #   volumes:
  #     - ./orders-microservice/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=postgresql://postgres:123456@order-db:5432/ordersdb?schema=public

  # order-db:
  #   container_name: orders-database
  #   image: postgres:16.2
  #   restart: always
  #   ports:
  #     - 5435:5432
  #   volumes:
  #     - ./orders-microservice/postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: ordersdb
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d ordersdb"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
